### PR TITLE
install jupyter kernel for julia

### PR DESCRIPTION
**Pull request by Moelf**
verified locally:
```
docker build -f Dockerfile -t julia:test1 . 
docker run -it julia:test1 bash 
root@576e2a70a427:/# ls /usr/local/share/jupyter/kernels/
julia-1.8  python3
```

### CODE REVIEW

**Comment by ivukotic** [comment]
There is already jupyter in that image. Have you tried Julia image from the web site?
Ilija


From: Jerry Ling ***@***.***>
Sent: Friday, July 29, 2022 20:49
To: ivukotic/ml_platform ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ivukotic/ml_platform] install jupyter kernel for julia (PR #11)


verified locally:

docker build -f Dockerfile -t julia:test1 .

docker run -it julia:test1 bash

***@***.***:/# ls /usr/local/share/jupyter/kernels/

julia-1.8  python3

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ivukotic/ml_platform/pull/11<https://urldefense.com/v3/__https:/github.com/ivukotic/ml_platform/pull/11__;!!BpyFHLRN4TMTrA!61J3uvuA6XnmRC9lOKmZS3yboX8_zMSONcI3pVLQluwxFMG3_UzEaZ3Bwcqfee2RFSzk2-Z-_nrUiFgszBVbtWJdhbFx$>

Commit Summary

  *   e6b37f3<https://urldefense.com/v3/__https:/github.com/ivukotic/ml_platform/pull/11/commits/e6b37f348223a20106909d57dc8078342d582b70__;!!BpyFHLRN4TMTrA!61J3uvuA6XnmRC9lOKmZS3yboX8_zMSONcI3pVLQluwxFMG3_UzEaZ3Bwcqfee2RFSzk2-Z-_nrUiFgszBVbtajYLxPd$> install jupyter kernel for julia

File Changes

(1 file<https://urldefense.com/v3/__https:/github.com/ivukotic/ml_platform/pull/11/files__;!!BpyFHLRN4TMTrA!61J3uvuA6XnmRC9lOKmZS3yboX8_zMSONcI3pVLQluwxFMG3_UzEaZ3Bwcqfee2RFSzk2-Z-_nrUiFgszBVbtTBR9ILE$>)

  *   M Dockerfile<https://urldefense.com/v3/__https:/github.com/ivukotic/ml_platform/pull/11/files*diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557__;Iw!!BpyFHLRN4TMTrA!61J3uvuA6XnmRC9lOKmZS3yboX8_zMSONcI3pVLQluwxFMG3_UzEaZ3Bwcqfee2RFSzk2-Z-_nrUiFgszBVbtQX8pghj$> (2)

Patch Links:

  *   https://github.com/ivukotic/ml_platform/pull/11.patch<https://urldefense.com/v3/__https:/github.com/ivukotic/ml_platform/pull/11.patch__;!!BpyFHLRN4TMTrA!61J3uvuA6XnmRC9lOKmZS3yboX8_zMSONcI3pVLQluwxFMG3_UzEaZ3Bwcqfee2RFSzk2-Z-_nrUiFgszBVbtTmIz8di$>
  *   https://github.com/ivukotic/ml_platform/pull/11.diff<https://urldefense.com/v3/__https:/github.com/ivukotic/ml_platform/pull/11.diff__;!!BpyFHLRN4TMTrA!61J3uvuA6XnmRC9lOKmZS3yboX8_zMSONcI3pVLQluwxFMG3_UzEaZ3Bwcqfee2RFSzk2-Z-_nrUiFgszBVbtdGMUoHn$>

**Comment by Moelf** [comment]
image

**Comment by Moelf** [comment]
this is to install kernel spec for Julia, not another Jupyter

**Pull request merged**
