### PR TITLE
add Julia

### PR DESCRIPTION
**Pull request by Moelf**
unfortunately python mpi wheels didn't compile for me locally, if there's way I can test/debug the docker on AF.uchicago let me know

cc @grabanal

### CODE REVIEW

**Comment by Moelf** [comment]
it is also possible for me to just add Julia to the existing `ml_platform`, in order to reduce image size I guess

**Comment by ivukotic** [comment]
If you want tell me how do you add Julia and I can create a special image with it. Maybe also remove some other things from it to make it smaller.
i

**Comment by Moelf** [comment]
this PR contains my attempts

**Comment by ivukotic** [comment]
Well, that did not work:
https://github.com/ivukotic/ml_platform/runs/7217343693?check_suite_focus=true

Ilija

**Comment by Moelf** [comment]
yeah that's the same error I encountered locally, but that hasn't got to the Julia part yet so the OpenAI folder is broken already?

**Comment by Moelf** [comment]
looks like it somewhat works:
```
Precompiling project...
  ✓ PyCall
  1 dependency successfully precompiled in 3 seconds. 285 already precompiled.
Removing intermediate container 22271aa12d8c
 ---> 8c6e6a6a2a46
Step 8/15 : RUN echo "Timestamp:" `date --utc` | tee /image-build-info.txt
 ---> Running in 653e046c92fa
Timestamp: Wed Jul 6 19:53:35 UTC 2022
Removing intermediate container 653e046c92fa
 ---> 9258ad2a6dff
Step 9/15 : COPY environment /environment
COPY failed: file not found in build context or excluded by .dockerignore: stat environment: file does not exist
```

not sure what the COPY should do

**Comment by ivukotic** [comment]
I manually added these changes. should work now.

**Comment by Moelf** [comment]
what do I have to do / wait until it becomes available?

**Pull request closed without merging**
